name: flutter_internet_signal
description: Package get internet signal using Flutter, the value is dBm.
version: 0.0.44
homepage: https://github.com/fellipeptc/flutter_internet_signal

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.prates.flutter_internet_signal
        pluginClass: FlutterInternetSignalPlugin
